"""add payment and coin_transactions tables

Revision ID: 6dc1e0d1c9de
Revises: 
Create Date: 2026-08-15 12:37:19.020232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dc1e0d1c9de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coin_transactions', 'feature',
               existing_type=sa.VARCHAR(length=50),
               comment="Джерело: 'shop_topup', 'tarot', 'fortune_cookie', 'gift', 'other'",
               existing_comment='Джерело: shop_topup, tarot, fortune_cookie, gift, other',
               existing_nullable=False)
    op.alter_column('qr_passes', 'is_on_territory',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint(None, 'qr_passes', ['telegram_id'])
    op.alter_column('scan_logs', 'scanned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('scan_logs_action_type_check'), 'scan_logs', type_='check')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'user_role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_check_constraint(op.f('scan_logs_action_type_check'), 'scan_logs', "action_type::text = ANY (ARRAY['in'::character varying, 'out'::character varying]::text[])")
    op.alter_column('scan_logs', 'scanned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'qr_passes', type_='unique')
    op.alter_column('qr_passes', 'is_on_territory',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('coin_transactions', 'feature',
               existing_type=sa.VARCHAR(length=50),
               comment='Джерело: shop_topup, tarot, fortune_cookie, gift, other',
               existing_comment="Джерело: 'shop_topup', 'tarot', 'fortune_cookie', 'gift', 'other'",
               existing_nullable=False)
    # ### end Alembic commands ###
